sms:
  notify_phonenum: "13071122875"
  api_url: 'http://sms.market.alicloudapi.com/singleSendSms'
  app_key: '23814070'
  app_secret: 'ff12790b50fc880f083e8520d6086af5'
  app_code: '6125ee74f7bd44ba9065f56a6672debb'
  sign_name: '壹刻珠宝'
  template_code: 'SMS_67155971'

db:
  mongo:
    host: "localhost"
    port: 27017
    database: "arbitrage"
    collections:
      trade: "trades"

arbitrage:
  currency_pairs: ['ETC_CNY', 'BTS_CNY', 'ZEC_CNY']
  exchanges: ['chbtc', 'yunbi', 'jubi', 'bter']

  check_interval_second: 1.05 #多久检查一次套利机会
  wait_order_filled_second: 10 
  query_order_state_interval_ms: 500

  BTS_CNY:
    arbitrage_exchanges: ['chbtc', 'jubi', 'yunbi']
    allow_slippage_perc: 0.001
    arbitrage_target_gain: 0.005
    balance_target_gain: 0.001
    balance_ratio: 0.1 #买币方币数/卖币方币数 < balance_ratio时，按照balance_target_gain算套利机会，否则用arbitrage_target_gain
    coin_trade_minimum: 5 #最少交易数量
    coin_trade_maximum: 500 #最多交易数量
    #风险控制，当alpha超过risk_alpha时不交易，主要是bter交易所，因为该交易所有可能返回其他币种的qoute，导致alpha异常大，但是是错的。
    risk_alpha: 0.1

    #using_withdraw 为True时，算收益要去掉提现手续费（币跟现金）
    using_withdraw: False

    ####当using_withdraw为true时才需要配下面的配置
    # withdraw_perc: 0.9
    # withdraw_minimum: 100

    # #只有当using_withdraw为True时，exchange_withdraw_permission才生效
    # exchange_withdraw_permission:
    #   btc38: False
    #   bter: False
    #   yunbi: False

    # # bts比较特殊，需要memo才能确保成功
    # exchange_withdraw_memo:
    #   yunbi: '75845781'


  ETC_CNY:
    arbitrage_exchanges: ['jubi', 'yunbi', 'chbtc']
    allow_slippage_perc: 0.0007
    arbitrage_target_gain: 0.004
    balance_target_gain: 0.001
    balance_ratio: 0.1 #买币方币数/卖币方币数 < balance_ratio时，按照balance_target_gain算套利机会，否则用arbitrage_target_gain
    coin_trade_minimum: 0.1 #最少交易数量
    coin_trade_maximum: 10 #最多交易数量
    #风险控制，当alpha超过risk_alpha时不交易，主要是bter交易所，因为该交易所有可能返回其他币种的qoute，导致alpha异常大，但是是错的。
    risk_alpha: 0.1

    #using_withdraw 为True时，算收益要去掉提现手续费（币跟现金）
    using_withdraw: False
    
  ANS_CNY:
    arbitrage_exchanges: ['yunbi', 'bter']
    allow_slippage_perc: 0.0007
    arbitrage_target_gain: 0.004
    balance_target_gain: 0.001
    balance_ratio: 0.1 
    coin_trade_minimum: 0.1 #最少交易数量
    coin_trade_maximum: 50 #最多交易数量
    risk_alpha: 0.1
    using_withdraw: False

  ZEC_CNY:
    arbitrage_exchanges: ['bter', 'yunbi']
    allow_slippage_perc: 0.0007
    arbitrage_target_gain: 0.004
    balance_target_gain: 0.0005
    balance_ratio: 0.1 
    coin_trade_minimum: 0.05 #最少交易数量
    coin_trade_maximum: 5 #最多交易数量
    risk_alpha: 0.1
    using_withdraw: False
  
  QTUM_CNY:
    arbitrage_exchanges: ['bter', 'yunbi']
    allow_slippage_perc: 0.0007
    arbitrage_target_gain: 0.004
    balance_target_gain: 0.0005
    balance_ratio: 0.1 
    coin_trade_minimum: 0.1 #最少交易数量
    coin_trade_maximum: 50 #最多交易数量
    risk_alpha: 0.1
    using_withdraw: False
  XRP_CNY:
    arbitrage_exchanges: ['bter', 'jubi']
    allow_slippage_perc: 0.0007
    arbitrage_target_gain: 0.004
    balance_target_gain: 0.001
    balance_ratio: 0.1
    coin_trade_minimum: 100 #最少交易数量
    coin_trade_maximum: 5000 #最多交易数量
    risk_alpha: 0.1
    using_withdraw: False

exchange:
  - name: chbtc
    access_key: 'key1'
    secret_key: 'key'
    max_order_retry: 5
    max_cancel_order_retry: 5
  - name: yunbi
    access_key: 'key'
    secret_key: 'key'
    max_order_retry: 5
    max_cancel_order_retry: 5
  - name: jubi
    access_key: 'key'
    secret_key: 'key'
    max_order_retry: 5
    max_cancel_order_retry: 5
  - name: bter
    access_key: 'key'
    secret_key: 'key'
    max_order_retry: 5
    max_cancel_order_retry: 5
