sms:
  api_url: 'http://sms.market.alicloudapi.com/singleSendSms'
  app_key: '23814070'
  app_secret: 'ff12790b50fc880f083e8520d6086af5'
  app_code: '6125ee74f7bd44ba9065f56a6672debb'

arbitrage:
  currency_pairs: ['ETC_CNY', 'BTS_CNY']
  exchanges: ['bter', 'chbtc', 'btc38', 'yunbi']

  check_interval_second: 1.5 #多久检查一次套利机会
  wait_order_filled_second: 10 
  query_order_state_interval_ms: 500

  arbitrage_target_gain: 0.006
  balance_target_gain: 0.001
  balance_ratio: 0.1 #买币方币数/卖币方币数 < balance_ratio时，按照balance_target_gain算套利机会，否则用arbitrage_target_gain
  coin_trade_minimum: #最少交易数量
    ETC_CNY: 0.1
    BTS_CNY: 20
  coin_trade_maximum: #最多交易数量
    ETC_CNY: 100
    # BTS_CNY: 110
    BTS_CNY: 10000

  BTS_CNY:
    arbitrage_exchanges: ['bter', 'yunbi']
    # arbitrage_exchanges: ['btc38', 'yunbi']
    allow_slippage_perc: 0.001
    #using_withdraw 为True时，算收益要去掉提现手续费（币跟现金）
    using_withdraw: False
    withdraw_perc: 0.9
    withdraw_minimum: 100

    #只有当using_withdraw为True时，exchange_withdraw_permission才生效
    exchange_withdraw_permission:
      btc38: False
      bter: False
      yunbi: False

    # bts比较特殊，需要memo才能确保成功
    exchange_withdraw_memo:
      yunbi: '75845781'


  ETC_CNY:
    arbitrage_exchanges: ['chbtc', 'yunbi']
    allow_slippage_perc: 0.0007

    #using_withdraw 为True时，算收益要去掉提现手续费（币跟现金）
    using_withdraw: False
    withdraw_perc: 0.9
    withdraw_minimum: 100

    #只有当using_withdraw为True时，exchange_withdraw_permission才生效
    exchange_withdraw_permission:
      btc38: False
      bter: False
      yunbi: False

    # bts比较特殊，需要memo才能确保成功
    exchange_withdraw_memo:
      yunbi: ''

exchange:
  - name: bter
    access_key: '24F6B6F0-E43C-482F-9BE3-F135F40BBFF8'
    secret_key: '92283cf7bc98afceefdc449359670ad1c6d70238ca202db6c1f34637a29f82e4'
    max_order_retry: 5
    max_cancel_order_retry: 5
  - name: chbtc
    access_key: 'a9e1f09e-1459-44df-8aea-024d97c37487'
    secret_key: '4086a247-092a-4893-ac4c-62c2f6ee6242'
    max_order_retry: 5
    max_cancel_order_retry: 5
  - name: btc38
    access_key: '498c1b144488bf99ff7eee444a5db618'
    secret_key: 'b93381bc0c6a88606fe7522ad0a4f51ac36fdc1a29446927b0f4ab615d4796c5'
    user_id: "195563"
    withdraw_proxy_url: "http://127.0.0.1:10010/bter/withdraw"
    rk_withdraw_secret_key: 'dc449359670ad1c6d70238ca202db6c1f34637a29f82e4' #必须跟proxy brower的key配置一致
    max_order_retry: 5
    max_cancel_order_retry: 5
  - name: yunbi
    access_key: 'gmSnwZZOiQTC4O90TozKE7JffCWxKEXxUGDOli9x'
    secret_key: '22xL90c7ImcxabkG6WfqS8VwOB2H2K9UQkxUrfJl'
    max_order_retry: 5
    max_cancel_order_retry: 5

